name: (master) [backend] Backend Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend-master.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: master
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd Teknofest-Kitchen-Arabic-Platform-Ibtikar
            git checkout master
            git pull
            git pull origin master
            cd backend

            # insert all environment variables into .env file
            cat > .env << 'ENVEOF'
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          SMTP_HOST=${{ vars.SMTP_HOST }}
          SMTP_PORT=${{ vars.SMTP_PORT }}
          SMTP_USER=${{ vars.SMTP_USER }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
          ADMIN_REGISTRATION_CODE=${{ secrets.ADMIN_REGISTRATION_CODE }}
          SUPER_ADMIN_USERNAME=${{ vars.SUPER_ADMIN_USERNAME }}
          SUPER_ADMIN_PASSWORD=${{ secrets.SUPER_ADMIN_PASSWORD }}
          ENVEOF

            docker stop tk-kitchen-be || true
            docker rm tk-kitchen-be || true
            docker build -t tk-kitchen-be . && docker run -d --name tk-kitchen-be --env-file .env -p 9680:9680 tk-kitchen-be
            docker network create tk-kitchen
            docker network connect tk-kitchen tk-kitchen-be
          EOF